// <auto-generated />
using System;
using AirMark.AuditVault.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditVault.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314065617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirMark.AuditVault.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AirMark.AuditVault.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 14, 6, 56, 16, 672, DateTimeKind.Utc).AddTicks(2500),
                            Name = "CCN Pte Ltd"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 14, 6, 56, 16, 672, DateTimeKind.Utc).AddTicks(2500),
                            Name = "DHL Corp"
                        });
                });

            modelBuilder.Entity("AirMark.AuditVault.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 3, 14, 6, 56, 16, 672, DateTimeKind.Utc).AddTicks(2500),
                            Email = "admin@ccn.com",
                            PasswordHash = "$2a$11$UuwCkfWdGQPftsb.NcTM6Otty16FLUZN9bu0m3T2AJq3UQLZqID8a",
                            Role = "Admin",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 3, 14, 6, 56, 16, 672, DateTimeKind.Utc).AddTicks(2500),
                            Email = "auditor@ccn.com",
                            PasswordHash = "$2a$11$UuwCkfWdGQPftsb.NcTM6Otty16FLUZN9bu0m3T2AJq3UQLZqID8a",
                            Role = "Auditor",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 3, 14, 6, 56, 16, 672, DateTimeKind.Utc).AddTicks(2500),
                            Email = "admin@dhl.com",
                            PasswordHash = "$2a$11$UuwCkfWdGQPftsb.NcTM6Otty16FLUZN9bu0m3T2AJq3UQLZqID8a",
                            Role = "Admin",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 3, 14, 6, 56, 16, 672, DateTimeKind.Utc).AddTicks(2500),
                            Email = "auditor@dhl.com",
                            PasswordHash = "$2a$11$UuwCkfWdGQPftsb.NcTM6Otty16FLUZN9bu0m3T2AJq3UQLZqID8a",
                            Role = "Auditor",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("AirMark.AuditVault.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("AirMark.AuditVault.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Logs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirMark.AuditVault.Domain.Entities.User", "Uploader")
                        .WithMany("UploadedLogs")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("AirMark.AuditVault.Domain.Entities.User", b =>
                {
                    b.HasOne("AirMark.AuditVault.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AirMark.AuditVault.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AirMark.AuditVault.Domain.Entities.User", b =>
                {
                    b.Navigation("UploadedLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
